services:

  mysql:
    container_name: '${CONTAINER_PREFIX_NAME}-mysql'
    image: mysql:8.0.40
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - symfony-network

  php:
    container_name: '${CONTAINER_PREFIX_NAME}-php'
    build:
      context: ./php
    expose:
      - '9000'
    volumes:
      # code
      - ../app:/var/www/symfony
    networks:
      - symfony-network

  nginx:
    container_name: '${CONTAINER_PREFIX_NAME}-nginx'
    image: nginx:1.27.3
    ports:
      - '80:80'
    env_file:
      - .env
    volumes:
      # vhost
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # code
      - ../app:/var/www/symfony
      # logs
      - ./nginx/logs:/var/log/nginx:cached
    networks:
      - symfony-network
    depends_on:
      - php

networks:
  symfony-network: